/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ntsc_trx
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_NTSC_TRX_API_H
#define INCLUDED_NTSC_TRX_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ntsc_trx_EXPORTS
#define NTSC_TRX_API __GR_ATTR_EXPORT
#else
#define NTSC_TRX_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_NTSC_TRX_API_H */
